name: postgrest
description: PostgREST client for Dart. This library provides an ORM interface to PostgREST.
version: 1.0.0-dev.4
homepage: 'https://supabase.io'
repository: 'https://github.com/supabase/postgrest-dart'

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  http: ^0.13.0

dev_dependencies:
  collection: ^1.16.0
  lints: ^2.0.0
  test: ^1.21.4
