name: postgrest
description: PostgREST client for Dart. This library provides an ORM interface to PostgREST.
version: 0.1.10+1
homepage: 'https://supabase.io'
repository: 'https://github.com/supabase/postgrest-dart'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.15.4
